#!/usr/bin/env python3
"""Ingest a `benchtest-report` issue into bench/community/<issue#>.json and
regenerate bench/RESULTS.md from all stored reports.

Stdlib-only (runs on the GitHub Actions ubuntu runner, no model, no MLX).

  benchtest_ingest.py --issue-json <path> [--repo-root .]   # ingest one issue + regen
  benchtest_ingest.py --regen [--repo-root .]               # regen RESULTS.md only
  benchtest_ingest.py --selftest                            # parser self-check

The issue form (.github/ISSUE_TEMPLATE/benchtest-report.yml) wraps the benchtest
report in a ```markdown fence — that fence is the parse anchor. Reports come from
`qwisp benchtest` (swift/Sources/qwisp/Benchtest.swift), whose stability cell is
`ok` / `**LOOPY**` (≤v0.3.2) or `ok (0.93)` / `**LOOPY** (0.21)` (≥v0.3.3).
"""
import argparse
import json
import re
import statistics
import sys
from pathlib import Path

FENCE_RE = re.compile(r"```markdown\s*\n(.*?)\n```", re.DOTALL)
STAB_RE = re.compile(r"(ok|\*\*LOOPY\*\*)(?:\s*\(([\d.]+)\))?")


def parse_report(body: str) -> dict:
    """Parse the issue body (or a bare report) into a flat dict. Raises ValueError."""
    m = FENCE_RE.search(body)
    report = m.group(1) if m else body  # bare paste fallback
    vm = re.search(r"### qwisp benchtest v(\S+)", report)
    if not vm:
        raise ValueError("no '### qwisp benchtest v…' header found")
    env: dict[str, str] = {}
    rows = []
    for line in report.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")] if line.strip().startswith("|") else None
        if not cells or cells[0] in ("env", "test", "---", ":---"):
            continue
        if len(cells) == 2:
            env[cells[0]] = cells[1]
        elif len(cells) == 6:
            sm = STAB_RE.search(cells[5])
            if not sm:
                continue
            rows.append({
                "test": cells[0],
                "mode": cells[1],
                "ttft_s": float(cells[2].rstrip("s")),
                "tok_s": float(cells[3].split()[0]),
                "tokens": int(cells[4]),
                "stable": sm.group(1) == "ok",
                "ratio": float(sm.group(2)) if sm.group(2) else None,
            })
    if not rows:
        raise ValueError("no result rows parsed")
    chip_raw = env.get("chip", "?")
    cm = re.match(r"(.+?)(?:\s*\((\d+)-core GPU\))?$", chip_raw)
    disk_raw = env.get("disk", "")
    rm = re.search(r"read ([\d.]+) GB/s", disk_raw)
    ram = re.match(r"(\d+)\s*GB", env.get("RAM", ""))
    return {
        "version": vm.group(1),
        "chip": cm.group(1).strip(),
        "gpu_cores": int(cm.group(2)) if cm.group(2) else None,
        "ram_gb": int(ram.group(1)) if ram else None,
        "macos": env.get("macOS"),
        "nvme": disk_raw.split(",")[0].strip() or None,
        "read_gbs": float(rm.group(1)) if rm else None,
        "power": env.get("power"),
        "model": env.get("model"),
        "tier": env.get("tier"),
        "rows": rows,
    }


def regen_results(bench_dir: Path) -> str:
    reports = []
    for p in sorted((bench_dir / "community").glob("*.json"), key=lambda p: int(p.stem)):
        reports.append(json.loads(p.read_text()))
    md = [
        "# Community benchmark results",
        "",
        "Generated by `scripts/benchtest_ingest.py` from issues labeled `benchtest-report`"
        " — do not edit by hand. To contribute a row: `qwisp benchtest` and follow the"
        " one-click URL ([call for testers](https://github.com/penta2himajin/qwisp/issues/38)).",
        "",
    ]
    groups: dict[tuple, list] = {}
    for r in reports:
        groups.setdefault((r["chip"], r["gpu_cores"], r["ram_gb"], r["nvme"]), []).append(r)
    for (chip, cores, ram, nvme), rs in groups.items():
        issues = ", ".join(f"#{r['issue']}" for r in rs)
        gpu = f" ({cores}-core GPU)" if cores else ""
        md.append(f"## {chip}{gpu} · {ram} GB · {nvme or 'unknown disk'}")
        md.append("")
        md.append(f"{len(rs)} report(s): {issues} · tier: {rs[0].get('tier', '?')}")
        md.append("")
        md.append("| test | mode | median decode | median TTFT | LOOPY rate |")
        md.append("|---|---|---|---|---|")
        cells: dict[tuple, list] = {}
        for r in rs:
            for row in r["rows"]:
                cells.setdefault((row["test"], row["mode"]), []).append(row)
        for (test, mode), rows in cells.items():
            loopy = sum(1 for x in rows if not x["stable"])
            md.append("| %s | %s | %.1f tok/s | %.1fs | %d/%d |" % (
                test, mode,
                statistics.median(x["tok_s"] for x in rows),
                statistics.median(x["ttft_s"] for x in rows),
                loopy, len(rows)))
        md.append("")
    if not reports:
        md.append("_No reports ingested yet._")
        md.append("")
    return "\n".join(md)


FIXTURE_OLD = """### benchtest output

```markdown
### qwisp benchtest v0.3.2

| env | |
|---|---|
| chip | Apple M1 Max (32-core GPU) |
| RAM | 64 GB |
| macOS | Version 26.5.2 (Build 25F84) |
| disk | APPLE SSD AP1024R, 995 GB, read 3.5 GB/s |
| power | AC, thermal nominal |
| model | Youssofal--Qwen3.6-35B-A3B-MTPLX-Optimized-Speed-FP16 |
| tier | resident C=256 → strict (lossless) |

| test | mode | TTFT | decode | tokens | stability |
|---|---|---|---|---|---|
| code-256 | strict | 1.3s | 87.1 tok/s | 256 | ok |
| nl-256 | strict | 1.2s | 91.5 tok/s | 256 | ok |
| long-600 | strict | 1.2s | 85.2 tok/s | 600 | ok |

tail of long-600: `…x`

_greedy; TTFT includes prefill; 16s total._
```

### Notes (optional)

_No response_
"""

FIXTURE_NEW = FIXTURE_OLD.replace("v0.3.2", "v0.3.3") \
    .replace("| 256 | ok |", "| 256 | ok (0.97) |") \
    .replace("| 600 | ok |", "| 600 | **LOOPY** (0.21) |")


def selftest() -> bool:
    old = parse_report(FIXTURE_OLD)
    assert old["chip"] == "Apple M1 Max" and old["gpu_cores"] == 32, old
    assert old["ram_gb"] == 64 and old["read_gbs"] == 3.5 and old["nvme"] == "APPLE SSD AP1024R"
    assert len(old["rows"]) == 3 and all(r["stable"] for r in old["rows"])
    assert old["rows"][0]["tok_s"] == 87.1 and old["rows"][0]["ttft_s"] == 1.3
    assert old["rows"][0]["ratio"] is None  # ≤v0.3.2 boolean format
    new = parse_report(FIXTURE_NEW)
    assert new["rows"][0]["ratio"] == 0.97 and new["rows"][0]["stable"]
    assert not new["rows"][2]["stable"] and new["rows"][2]["ratio"] == 0.21
    try:
        parse_report("hello, no report here")
        raise AssertionError("garbage should not parse")
    except ValueError:
        pass
    import tempfile
    with tempfile.TemporaryDirectory() as d:
        comm = Path(d) / "community"
        comm.mkdir()
        for n, fx in ((36, FIXTURE_OLD), (99, FIXTURE_NEW)):
            comm.joinpath(f"{n}.json").write_text(json.dumps({"issue": n, **parse_report(fx)}))
        out = regen_results(Path(d))
        assert "## Apple M1 Max (32-core GPU) · 64 GB · APPLE SSD AP1024R" in out
        assert "2 report(s): #36, #99" in out and "| 1/2 |" in out, out
    print("INGEST SELFTEST PASS")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--issue-json", help="path to the GitHub event's issue object (JSON)")
    ap.add_argument("--regen", action="store_true")
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        return 0 if selftest() else 1
    bench = Path(args.repo_root) / "bench"
    if args.issue_json:
        issue = json.loads(Path(args.issue_json).read_text())
        data = {"issue": issue["number"], "title": issue.get("title", ""),
                **parse_report(issue.get("body") or "")}
        out = bench / "community" / f"{issue['number']}.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(data, indent=1) + "\n")
        print(f"wrote {out}")
    elif not args.regen:
        ap.error("one of --issue-json / --regen / --selftest required")
    (bench / "RESULTS.md").write_text(regen_results(bench))
    print(f"wrote {bench / 'RESULTS.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
